services:
  web:
    build: .
    env_file:
      - docker/env/web
    user: "${UID:-1000}:${GID:-1000}"
    working_dir: /srv/app
    stdin_open: true  # `-i`
    tty: true  # `-t`
    volumes:
       - ${PWD}:/srv/app
    network_mode: host
